--1
drop table MOVIES;
CREATE TABLE MOVIES(
    ID NUMBER(12) PRIMARY KEY,
    TITLE VARCHAR2(400) NOT NULL,
    CATEGORY VARCHAR2(50),
    YEAR CHAR(12),
    CAST VARCHAR2(4000),
    DIRECTOR VARCHAR2(4000),
    STORY VARCHAR2(4000),
    PRICE NUMBER(5, 2),
    COVER BLOB,
    MIME_TYPE VARCHAR2(50)
);

--2
INSERT INTO MOVIES
SELECT ID, TITLE, CATEGORY, YEAR, CAST, DIRECTOR,
STORY, PRICE, IMAGE AS COVER, MIME_TYPE
FROM DESCRIPTIONS D LEFT JOIN COVERS C ON D.ID = C.MOVIE_ID;

--3
SELECT ID, TITLE FROM MOVIES WHERE COVER IS NULL;

--4
SELECT ID, TITLE, DBMS_LOB.GETLENGTH(COVER) AS FILESIZE FROM MOVIES
WHERE COVER IS NOT NULL;

--5
SELECT ID, TITLE, DBMS_LOB.GETLENGTH(COVER) AS FILESIZE FROM MOVIES
WHERE COVER IS NULL;

--6
SELECT DIRECTORY_NAME, DIRECTORY_PATH FROM ALL_DIRECTORIES;

--7
UPDATE MOVIES SET COVER=EMPTY_BLOB(), MIME_TYPE = 'image/jpg'
WHERE ID=66;
COMMIT;

--8
SELECT ID, TITLE, DBMS_LOB.GETLENGTH(COVER) AS FILESIZE FROM MOVIES
WHERE ID = 65 OR ID = 66;

--9
DECLARE
    fil BFILE := BFILENAME('ZSBD_DIR', 'escape.jpg');
    lobd BLOB;
BEGIN
    SELECT COVER INTO lobd FROM MOVIES WHERE ID=66 FOR UPDATE;
    DBMS_LOB.FILEOPEN(fil, DBMS_LOB.file_readonly);
    DBMS_LOB.LOADFROMFILE(lobd, fil, DBMS_LOB.GETLENGTH(fil));
    DBMS_LOB.FILECLOSE(fil);
    COMMIT;
END;

--10
CREATE TABLE TEMP_COVERS(
    MOVIE_ID NUMBER(12),
    IMAGE BFILE,
    MIME_TYPE VARCHAR2(50)
);

--11
INSERT INTO TEMP_COVERS
VALUES(65, BFILENAME('ZSBD_DIR', 'eagles.jpg'), 'image/jpg');

--12
SELECT DBMS_LOB.GETLENGTH(IMAGE) FROM TEMP_COVERS;

--13
DECLARE
    lobd BLOB;
    fil TEMP_COVERS.IMAGE%TYPE;
    mime TEMP_COVERS.MIME_TYPE%TYPE;
BEGIN
    SELECT IMAGE, MIME_TYPE INTO fil, mime FROM TEMP_COVERS
    WHERE MOVIE_ID = 65;
    
    DBMS_LOB.CREATETEMPORARY(lobd, TRUE);
    DBMS_LOB.FILEOPEN(fil, DBMS_LOB.FILE_READONLY);
    DBMS_LOB.LOADFROMFILE(lobd, fil, DBMS_LOB.GETLENGTH(fil));
    DBMS_LOB.FILECLOSE(fil);
    
    UPDATE MOVIES SET COVER = lobd, MIME_TYPE = mime
    WHERE ID = 65;
    DBMS_LOB.freetemporary(lobd);
    COMMIT;
END;

--14
SELECT ID, DBMS_LOB.GETLENGTH(COVER) FROM MOVIES WHERE ID = 65 OR ID = 66;

--15
DROP TABLE MOVIES;
DROP TABLE TEMP_COVERS;