--1
CREATE TABLE DOKUMENTY (
    ID NUMBER(12) PRIMARY KEY,
    DOKUMENT CLOB
);

--2
DECLARE
    LOBD CLOB;
    I INTEGER;
BEGIN
    INSERT INTO DOKUMENTY VALUES(1, EMPTY_CLOB());
    SELECT DOKUMENT INTO LOBD FROM DOKUMENTY WHERE ID = 1 FOR UPDATE;
    FOR I IN 1..10000 LOOP
        DBMS_LOB.APPEND(LOBD, 'Oto tekst. ');
    END LOOP;
    
    COMMIT;
END;

--3a
SELECT * FROM DOKUMENTY;

--3b
SELECT UPPER(DOKUMENT) FROM DOKUMENTY;

--3c
SELECT LENGTH(DOKUMENT) FROM DOKUMENTY;

--3d
SELECT DBMS_LOB.GETLENGTH(DOKUMENT) FROM DOKUMENTY;

--3e
SELECT SUBSTR(DOKUMENT, 5, 1000) FROM DOKUMENTY;

--3f
SELECT DBMS_LOB.SUBSTR(DOKUMENT, 1000, 5) FROM DOKUMENTY;

--4
INSERT INTO DOKUMENTY VALUES (2, EMPTY_CLOB());

--5
INSERT INTO DOKUMENTY VALUES (3, NULL);
COMMIT;

--6
SELECT * FROM DOKUMENTY;
SELECT UPPER(DOKUMENT) FROM DOKUMENTY;
SELECT LENGTH(DOKUMENT) FROM DOKUMENTY;
SELECT DBMS_LOB.GETLENGTH(DOKUMENT) FROM DOKUMENTY;
SELECT SUBSTR(DOKUMENT, 5, 1000) FROM DOKUMENTY;
SELECT DBMS_LOB.SUBSTR(DOKUMENT, 1000, 5) FROM DOKUMENTY;

--7
SELECT DIRECTORY_NAME, DIRECTORY_PATH FROM ALL_DIRECTORIES;

--8
DECLARE
    LOBD CLOB;
    FILS BFILE := BFILENAME('ZSBD_DIR', 'dokument.txt');
    DOFFSET INTEGER := 1;
    SOFFSET INTEGER := 1;
    LANGCTX INTEGER := 0;
    WARN INTEGER := NULL;
BEGIN
    SELECT DOKUMENT INTO LOBD FROM DOKUMENTY WHERE ID = 2 FOR UPDATE;
    
    DBMS_LOB.FILEOPEN(FILS, DBMS_LOB.FILE_READONLY);
    DBMS_LOB.LOADCLOBFROMFILE(LOBD, FILS, DBMS_LOB.LOBMAXSIZE, DOFFSET, SOFFSET, 0, LANGCTX, WARN);
    DBMS_LOB.FILECLOSE(FILS);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Status operacji: ' || warn);
END;

--9
UPDATE DOKUMENTY SET DOKUMENT = TO_CLOB(BFILENAME('ZSBD_DIR', 'dokument.txt')) WHERE ID = 3;

--10
SELECT * FROM DOKUMENTY;

--11
SELECT DBMS_LOB.GETLENGTH(DOKUMENT) FROM DOKUMENTY;

--12
DROP TABLE DOKUMENTY;

--13
CREATE OR REPLACE PROCEDURE CLOB_CENSOR (
    LOBD IN OUT CLOB,
    SUBSTR VARCHAR2
) IS
    POSITION INTEGER;
    REPLACEMENT VARCHAR2(100);
    I INTEGER;
BEGIN
    FOR I IN 1..LENGTH(SUBSTR) LOOP
        REPLACEMENT := REPLACEMENT || '.';
    END LOOP;
    
    LOOP
        POSITION := DBMS_LOB.INSTR(LOBD, SUBSTR, 1, 1);
        EXIT WHEN POSITION = 0;
        DBMS_LOB.WRITE(LOBD, LENGTH(SUBSTR), POSITION, REPLACEMENT);
    END LOOP;
END CLOB_CENSOR;

--14
CREATE TABLE BIOGRAPHIES_COPY AS
SELECT * FROM ZSBD_TOOLS.BIOGRAPHIES;

DECLARE
    LOBD CLOB;
BEGIN
    SELECT BIO INTO LOBD FROM BIOGRAPHIES_COPY WHERE ID = 1 FOR UPDATE;
    CLOB_CENSOR(LOBD, 'Cimrman');
    COMMIT;
END;

SELECT * FROM BIOGRAPHIES_COPY;

--15
DROP TABLE BIOGRAPHIES_COPY;
