--1a
select lpad('-',2*(level-1),'|-') || t.owner||'.'||t.type_name||' (FINAL:'||t.final||
', INSTANTIABLE:'||t.instantiable||', ATTRIBUTES:'||t.attributes||', METHODS:'||t.methods||')'
from all_types t
start with t.type_name = 'ST_GEOMETRY'
connect by prior t.type_name = t.supertype_name
 and prior t.owner = t.owner;
 
--1b
select distinct m.method_name
from all_type_methods m
where m.type_name like 'ST_POLYGON'
and m.owner = 'MDSYS'
order by 1;

--1c
CREATE TABLE MYST_MAJOR_CITIES(
    FIPS_CNTRY VARCHAR2(2),
    CITY_NAME VARCHAR2(40),
    STGEOM ST_POINT
)

--1d
INSERT INTO MYST_MAJOR_CITIES
SELECT FIPS_CNTRY, CITY_NAME, TREAT(ST_POINT.FROM_SDO_GEOM(GEOM) AS ST_POINT) AS STGEOM
FROM MAJOR_CITIES;

--2a
INSERT INTO MYST_MAJOR_CITIES
VALUES ('PL', 'Szczyrk', TREAT(ST_POINT.FROM_WKT('POINT (19.036107 49.718655)') AS ST_POINT));

--2b
SELECT NAME, ST_POINT.FROM_SDO_GEOM(GEOM).GET_WKT() AS WKT
FROM RIVERS;

--2c
SELECT SDO_UTIL.TO_GMLGEOMETRY(ST_POINT.GET_SDO_GEOM(STGEOM)) AS GML
FROM MYST_MAJOR_CITIES M
WHERE CITY_NAME = 'Szczyrk';

--3a
CREATE TABLE MYST_COUNTRY_BOUNDARIES(
    FIPS_CNTRY VARCHAR2(2),
    CNTRY_NAME VARCHAR2(40),
    STGEOM ST_MULTIPOLYGON
)

--3b
INSERT INTO MYST_COUNTRY_BOUNDARIES
SELECT FIPS_CNTRY, CNTRY_NAME, ST_MULTIPOLYGON(GEOM)
FROM COUNTRY_BOUNDARIES;

--3c
SELECT M.STGEOM.ST_GEOMETRYTYPE(), COUNT(*)
FROM MYST_COUNTRY_BOUNDARIES M
GROUP BY M.STGEOM.ST_GEOMETRYTYPE();

--3d
SELECT M.STGEOM.ST_ISSIMPLE()
FROM MYST_COUNTRY_BOUNDARIES M;

--4a
--UPDATE MYST_MAJOR_CITIES C
--SET C.STGEOM = ST_POINT(C.STGEOM.ST_X(), C.STGEOM.ST_Y(), 8307)
--WHERE C.CITY_NAME = 'Szczyrk';

SELECT B.CNTRY_NAME, COUNT(*)
FROM MYST_COUNTRY_BOUNDARIES B, MYST_MAJOR_CITIES C
WHERE C.STGEOM.ST_WITHIN(B.STGEOM) = 1
GROUP BY B.CNTRY_NAME;

--4b
SELECT A.CNTRY_NAME, B.CNTRY_NAME
FROM MYST_COUNTRY_BOUNDARIES A, MYST_COUNTRY_BOUNDARIES B
WHERE B.CNTRY_NAME = 'Czech Republic' AND B.STGEOM.ST_TOUCHES(A.STGEOM) = 1;

--4c
SELECT DISTINCT B.CNTRY_NAME, R.NAME
FROM MYST_COUNTRY_BOUNDARIES B, RIVERS R
WHERE ST_LINESTRING(R.GEOM).ST_INTERSECTS(B.STGEOM) = 1 AND B.CNTRY_NAME = 'Czech Republic';

--4d
SELECT TREAT(A.STGEOM.ST_Union(B.STGEOM) AS ST_POLYGON).ST_AREA() AS POWIERZCHNIA
FROM MYST_COUNTRY_BOUNDARIES A, MYST_COUNTRY_BOUNDARIES B
WHERE A.CNTRY_NAME = 'Czech Republic' AND B.CNTRY_NAME = 'Slovakia';

--4e
SELECT B.STGEOM.ST_GEOMETRYTYPE() AS OBIEKT, B.STGEOM.ST_DIFFERENCE(ST_GEOMETRY(W.GEOM)).ST_GEOMETRYTYPE() AS WEGRY_BEZ
FROM MYST_COUNTRY_BOUNDARIES B, WATER_BODIES W
WHERE B.CNTRY_NAME = 'Hungary' AND W.NAME = 'Balaton';

--5a
--EXPLAIN PLAN FOR
SELECT COUNT(*)
FROM MYST_MAJOR_CITIES C, MYST_COUNTRY_BOUNDARIES B
WHERE B.CNTRY_NAME = 'Poland' AND SDO_WITHIN_DISTANCE(B.STGEOM, C.STGEOM, 'distance=100 unit=km') = 'TRUE';

--SELECT PLAN_TABLE_OUTPUT
--FROM TABLE(DBMS_XPLAN.DISPLAY)

--5b
INSERT INTO USER_SDO_GEOM_METADATA
SELECT 'MYST_MAJOR_CITIES', 'STGEOM', T.DIMINFO, T.SRID
FROM ALL_SDO_GEOM_METADATA T
WHERE T.TABLE_NAME = 'MAJOR_CITIES';

--5C
CREATE INDEX MYST_MAJOR_CITIES_INDEX
ON MYST_MAJOR_CITIES(STGEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

--5D
EXPLAIN PLAN FOR
SELECT COUNT(*)
FROM MYST_MAJOR_CITIES C, MYST_COUNTRY_BOUNDARIES B
WHERE B.CNTRY_NAME = 'Poland' AND SDO_WITHIN_DISTANCE(B.STGEOM, C.STGEOM, 'distance=100 unit=km') = 'TRUE';

SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY)