--1a
--DROP TABLE A6_LRS;
CREATE TABLE A6_LRS (
    GEOM SDO_GEOMETRY
);

--1b
INSERT INTO A6_LRS
SELECT S.GEOM
FROM STREETS_AND_RAILROADS S, MAJOR_CITIES M
WHERE SDO_RELATE(S.GEOM, SDO_GEOM.SDO_BUFFER(M.GEOM, 10, 1, 'unit=km'), 'MASK=ANYINTERACT') = 'TRUE' AND M.CITY_NAME = 'Koszalin';

--1c
SELECT SDO_GEOM.SDO_LENGTH(A.GEOM, 1, 'unit=km') AS DISTANCE, ST_LINESTRING(A.GEOM).ST_NUMPOINTS() AS ST_NUMPOINTS
FROM A6_LRS A;

--1d
UPDATE A6_LRS
SET GEOM = SDO_LRS.CONVERT_TO_LRS_GEOM(GEOM, 0, SDO_GEOM.SDO_LENGTH(GEOM, 1, 'unit=km'));

--1e
INSERT INTO USER_SDO_GEOM_METADATA(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES(
    'A6_LRS',
    'GEOM',
    MDSYS.SDO_DIM_ARRAY(
     MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
     MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
     MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1)),
    8307
);

--1f
CREATE INDEX A6_LRS_IDX
ON A6_LRS(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

--2a
SELECT SDO_LRS.VALID_MEASURE(GEOM, 500)
FROM A6_LRS;

--2b
SELECT SDO_LRS.GEOM_SEGMENT_END_PT(GEOM)
FROM A6_LRS;

--2c
SELECT SDO_LRS.LOCATE_PT(GEOM, 150, 0)
FROM A6_LRS;

--2d
SELECT SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160)
FROM A6_LRS;

--2e
SELECT SDO_LRS.PROJECT_PT(A.GEOM, M.GEOM)
FROM A6_LRS A, MAJOR_CITIES M
WHERE M.CITY_NAME = 'Slupsk';

--2f
SELECT SDO_GEOM.SDO_LENGTH(SDO_LRS.OFFSET_GEOM_SEGMENT(A.GEOM, U.DIMINFO, 50, 200, 50, 'unit=m'), 1, 'unit=km')
FROM A6_LRS A, USER_SDO_GEOM_METADATA U
WHERE U.COLUMN_NAME = 'GEOM' AND U.TABLE_NAME = 'A6_LRS';