--1
CREATE TABLE CYTATY AS
SELECT * FROM ZSBD_TOOLS.CYTATY;

--2
SELECT AUTOR, TEKST
FROM CYTATY
WHERE LOWER(TEKST) LIKE '%optymista%' OR LOWER(TEKST) LIKE '%optymista%';

--3
CREATE INDEX CYTATY_INDEX
ON CYTATY(TEKST)
INDEXTYPE IS CTXSYS.CONTEXT;

--4
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'pesymista AND optymista') > 0;

--5
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'pesymista NOT optymista') > 0;

--6
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'NEAR((optymista, pesymista), 3)') > 0;

--7
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'NEAR((optymista, pesymista), 10)') > 0;

--8
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, '?yci%') > 0;

--9
SELECT AUTOR, TEKST, SCORE(1)
FROM CYTATY
WHERE CONTAINS(TEKST, '?yci%', 1) > 0;

--10
SELECT AUTOR, TEKST, SCORE(1) AS DOPASOWANIE
FROM CYTATY
WHERE CONTAINS(TEKST, '?yci%', 1) > 0
ORDER BY DOPASOWANIE DESC
FETCH FIRST 1 ROW ONLY;

--11
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'FUZZY(probelm, , , N)') > 0;

--12
INSERT INTO CYTATY
VALUES(39, 'Bertrand Russell', 'To smutne, ?e glupcy sa tacy pewni siebie, a ludzie rozsadni tacy pelni watpliwosci');
COMMIT;

--13
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'GLUPCY') > 0;
--NIEZAKUTALIZOWANY INDEKS

--14
SELECT *
FROM DR$CYTATY_INDEX$I;

--15
DROP INDEX CYTATY_INDEX;

CREATE INDEX CYTATY_INDEX
ON CYTATY(TEKST)
INDEXTYPE IS CTXSYS.CONTEXT;

--16
SELECT *
FROM DR$CYTATY_INDEX$I;

SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'GLUPCY') > 0;

--17
DROP INDEX CYTATY_INDEX;
DROP TABLE CYTATY;

--1
CREATE TABLE QUOTES AS
SELECT * FROM ZSBD_TOOLS.QUOTES;

--2
CREATE INDEX QOUTES_INDEX
ON QUOTES(TEXT)
INDEXTYPE IS CTXSYS.CONTEXT;

--3
SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, 'work') > 0;

SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, '$work') > 0;

SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, 'working') > 0;

SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, '$working') > 0;

--4
SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, 'it') > 0;

-- SLOWO 'IT' NALEZY DO STOP-LISTY I NIE ZNAJDUJE SIE W INDEKSIE

--5
SELECT *
FROM CTX_STOPLISTS;
--DEFAULT_STOPLIST

--6
SELECT *
FROM CTX_STOPWORDS;

--7
--DROP INDEX QOUTES_INDEX;
--DROP INDEX QUOTES_INDEX;

CREATE INDEX QUOTES_INDEX
ON QUOTES(TEXT)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS ('stoplist CTXSYS.EMPTY_STOPLIST');

--8
SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, 'it') > 0;
--TAK

--9
SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, 'fool AND humans') > 0;

--10
SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, 'fool AND computer') > 0;

--11
SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, '(fool AND computer) WITHIN SENTENCE') > 0;

-- SENTENCE NIE JEST DODANY DO GRUP SEKCJI

--12
DROP INDEX QUOTES_INDEX;

--13
begin
 ctx_ddl.create_section_group('nullgroup', 'NULL_SECTION_GROUP');
 ctx_ddl.add_special_section('nullgroup', 'SENTENCE');
 ctx_ddl.add_special_section('nullgroup', 'PARAGRAPH');
end;

--14
CREATE INDEX QUOTES_INDEX
ON QUOTES(TEXT)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS ('stoplist CTXSYS.EMPTY_STOPLIST section group nullgroup');

--15
SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, '(fool AND humans) WITHIN SENTENCE') > 0;

SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, '(fool AND computer) WITHIN SENTENCE') > 0;

--16
SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, 'humans') > 0;
-- W INDEKSIE NIE ZOSTALO STWORZONE SLOWO NON-HUMANS TYLKO ZOSTALO PODZIELONE NA DWA OSOBNE 'NON' I 'HUMANS'

--17
DROP INDEX QUOTES_INDEX;

begin
 ctx_ddl.create_preference('lex_z_m','BASIC_LEXER');
 ctx_ddl.set_attribute('lex_z_m','printjoins', '-');
 ctx_ddl.set_attribute ('lex_z_m','index_text', 'YES');
end;

CREATE INDEX QUOTES_INDEX
ON QUOTES(TEXT)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS ('stoplist CTXSYS.EMPTY_STOPLIST section group nullgroup LEXER lex_z_m');

--18
SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, 'humans') > 0;
--NIE

--19
SELECT AUTHOR, TEXT
FROM QUOTES
WHERE CONTAINS(TEXT, 'NON\-humans') > 0;

--20
DROP TABLE QUOTES;
BEGIN
    CTX_DDL.DROP_PREFERENCE('lex_z_m');
    CTX_DDL.DROP_SECTION_GROUP('nullgroup');
END;
